<?php //

/**
 * @file
 * Enables search using simple search api.
 */



/**
 * Implements hook_ctools_plugin_directory().
 *
 * It simply tells panels where to find the .inc files that define various
 * args, contexts, content_types.
 */
function white_design_ctools_plugin_directory($module, $plugin) {
  if ($module == 'ctools' && !empty($plugin)) {
    return "plugins/$plugin";
  }
}

// function white_design_theme($existing, $type, $theme, $path) {
//   return array(
//     'ting_simple_search_covers' => array(
//       'variables' => array('results' => NULL),
//       'template' => 'covers-search-result',
//       'path' => $path . '/templates',
//     ),
//     'ting_simple_search_item' => array(
//       'variables' => array(
//         'title' => NULL,
//         'creators' => NULL,
//         'cover' => NULL,
//       ),
//       'template' => 'ting-simple-search-item',
//       'path' => $path . '/templates',
//     ),
//   );
// }
